version: "3.8"
services:
  nextjs-app:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env.local
    # Or specify individual variables:
    # environment:
    #   - DATABASE_URL=${DATABASE_URL}
    #   - API_KEY=${API_KEY}
